services:
  - type: web
    name: tipsi-menu-voice
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      npm install --prefix frontend
      npm run build --prefix frontend
      mkdir -p backend/frontend/assets
      cp frontend/public/beep.mp3 backend/frontend/
      cp frontend/public/ejemplo.webm backend/frontend/
      cp frontend/public/favicon.ico backend/frontend/
      cp -r frontend/dist/assets/* backend/frontend/assets/
      python manage.py collectstatic --noinput

    startCommand: gunicorn tipsiphoto.wsgi:application


    envVars:
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: ALLOWED_HOSTS
        value: tipsi-menu-voice.onrender.com
      - key: OPENAI_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: EMAIL_HOST
        value: smtp-relay.brevo.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        value: True
